[package]
name = "flux"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "flux"
path = "src/main.rs"

[dependencies]
flux-core = { path = "../core" }
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"